language: php

php: [5.3, 5.4, 5.5, 5.6, hhvm]

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer selfupdate
  - composer update

script:
  - vendor/bin/phpunit --coverage-text
  - vendor/bin/phpcs --standard=PSR2 src/
  - vendor/bin/phpmd src/ text cleancode,codesize,controversial,design,naming,unusedcode
